### ISSUE TITLE
bug - 5 in row

### ISSUE THREAD

**Issue by 221V** [altenwald/leprechaun#3]
i got 5 in row, but it now collects O_o
and previous collected stops animating O_o
https://i.imgur.com/seeqy0V.png

**Comment by manuel-rubio** [comment]
very weird, had you Internet issues during the gameplay? Only to try to figure out what could be happening, I couldn't reproduce it at the moment.

**Comment by manuel-rubio** [comment]
Ok, I know how to reproduce it...

1. Perform a move and then change to another different tab, the game tab should be in the background.
2. After a while, back to the game. It should be frozen in the way we left it but without new updates from slides.

I've to detect when the browser loses focus, and when the focus is recovered, perform a request to redraw the board.

**Comment by 221V** [comment]
also there are problem with new version on old pc --
phaser or not runs, or runs with big-big animations lag,
after big waiting time - black screen after page loaded, before game starts..

on new pc -- phaser also runs not without waiting time((

ohhh.. old version was without this perfomance problems, i like that version more :)

**Comment by manuel-rubio** [comment]
yes, I've added audios and everything (audio + sprites) takes longer to be downloaded. Phaser has the "problem" it's not starting until everything is downloaded. I'm going to add a loading bar at the beginning. See #4 

About the issue because of the lag, I think that was happening also in the old version, I had to use too much redraw action to ensure the board is showing fine. But I'm going to provide another URL because the WebSocket communication is still the same. See #5.
